### PR TITLE
add fix going to depart and arrive announce

### PR DESCRIPTION
**Pull request by tkhmy**
## Related Issue(required)
[Internal link](https://tier4.atlassian.net/browse/RT0-32213)

## Description(required)
- fix departing and arriving announce logic

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yabuta** [comment]
@tkhmy 
たぶんフラグが逆だったので修正しました
https://github.com/tier4/AutowareSignage/pull/108/commits/032ada5e8b9647d9b7b2c0e00554daab9b8ba35e

また、回送中になったら発進予告のフラグはリセットしてもいいかなと思うのでこちらにもフラグ解除を設定しました
https://github.com/tier4/AutowareSignage/pull/108/commits/cff83aa70aa35db2995f58621e7d981d7aa41c36

**Comment by tkhmy** [comment]
@yabuta 
私試しました。問題ないと思います。

**Comment by yabuta** [comment]
タンさんの確認がOKならマージしてしまう

**Comment by tkhmy** [comment]
@yabuta 試しました、問題ないです。
approveお願いします。

**Review by yabuta — APPROVED** [review]

**Pull request merged**
