### PR TITLE
add thread handlering

### PR DESCRIPTION
**Pull request by tkhmy**
## Related Issue(required)
[internal link](https://tier4.atlassian.net/browse/RT0-32961)

## Description(required)
- add thread to handle the fms, in case the internal is weak

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by dkoldaev** [comment]
Please note that there might be still issues in performance because python threads are subject to GIL. Did you try testing if this resolves the issues? 

Also, it looks like two threads can be executing the function at the same time. GIL will only protect the bytecode, but it is not guaranteed that the whole output will keep its integrity. 

Did you consider using `asyncio`? I believe both of the above issues can be solved with it

**Comment by tkhmy** [comment]
> Please note that there might be still issues in performance because python threads are subject to GIL. Did you try testing if this resolves the issues?
> 
> Also, it looks like two threads can be executing the function at the same time. GIL will only protect the bytecode, but it is not guaranteed that the whole output will keep its integrity.
> 
> Did you consider using `asyncio`? I believe both of the above issues can be solved with it

I not able to reproduce the issue in my laptop,because it is due to internet issue.
I create this PR, because the request is block when the internet is too slow. and the transition of the stage is been delay.
I do not think it is a performance issue, as the program itself do not take so much processing.

**Comment by dkoldaev** [comment]
> I not able to reproduce the issue in my laptop,because it is due to internet issue.

There are ways to test bad network on your local machine. You can use tool like [NetEM](https://www.opensourceforu.com/2012/06/bandwidth-throttling-netem-network-emulation/) to test your PR. I think it is not a good idea to merge a PR before it has been tested. I strongly recommend you testing your code before merging. Ideally, the code should have automated test that run in CI on every PR. just FYI, the setup script does not setup the code properly and some dependencies are missing (serial module in python). 


> I create this PR, because the request is block when the internet is too slow. and the transition of the stage is been delay.
> I do not think it is a performance issue, as the program itself do not take so much processing.

What I meant by performance issues is anything that makes the program run slowly including not properly handled network delays. And as I said above, your solution might not work in some cases, because python threads can still be blocking (note that you also use blocking HTTP client, there are async http clients like [aiohttp]([url](https://docs.aiohttp.org/en/stable/))).

**Comment by tkhmy** [comment]
> There are ways to test bad network on your local machine. You can use tool like [NetEM](https://www.opensourceforu.com/2012/06/bandwidth-throttling-netem-network-emulation/) to test your PR. I think it is not a good idea to merge a PR before it has been tested. I strongly recommend you testing your code before merging. Ideally, the code should have automated test that run in CI on every PR. 

Yes, I was not planning to merge it before we tested it, we already planned to test it in the problem vehicle.
But anyway thanks for sharing the kit, I will have a look.
The code has actually been tested in the release and also QA testing, but edge cases like network problems is really not in consideration initially.

> just FYI, the setup script does not setup the code properly and some dependencies are missing (serial module in python).****

Ya, this repository is not really well maintained, the setup instrustion of this repository is been done by another repository.

> What I meant by performance issues is anything that makes the program run slowly including not properly handled network delays. And as I said above, your solution might not work in some cases, because python threads can still be blocking (note that you also use blocking HTTP client, there are async http clients like aiohttp).
 
Thank you, I will have a look on the aiohttp

**Comment by tkhmy** [comment]
@yabuta 
ここはaiohttpに試しました、問題ないと思います。
ansibleも設定必要がありますが、何のbeta branchで修正しますか？

**Review by yabuta — APPROVED** [review]
LGTM

**Pull request merged**
